name: line test and build
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo into runner
        uses: actions/checkout@v3
      - name: install node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencise
        run: npm ci
      - name: run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo into runner
        uses: actions/checkout@v3
      - name: install node jobs
        uses: actions/setup-node@v3
        with:
           node-version: 18
      - name: install dependencise
        run: npm ci
      - name: run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: clone repo into runner
        uses: actions/checkout@v3
      - name: install node jobs
        uses: actions/setup-node@v3
        with:
           node-version: 18
      - name: install dependencise
        run: npm ci
      - name: build the code
        run: npm run build
      - name: deploy the website
        run: echo "we are finalling deploying the site "


      