name: Lint, Test, and Build
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo into runner
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo into runner
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test

  deploy:
    needs: [lint, test]  # ✅ Now depends on both lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo into runner
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Deploy the website
        run: echo "We are finally deploying the site"
